### ISSUE TITLE
Support python >3.11

### ISSUE THREAD

**Issue by vkkodali** [DessimozLab/OMArk#12]
I am getting the following error when I try to install using the PyPI package: 
```
$ pip install omark
...
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7w1t_vv2/numba_98834001f5d44d129c594eaf45126ad3/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-7w1t_vv2/numba_98834001f5d44d129c594eaf45126ad3/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
      [end of output]
```

Is there anything specific that requires the python version to be <3.11? Can the requirements be amended to include python versions above 3.11 as well?

**Comment by YanNevers** [comment]
Hello @vkkodali. 

It appears this is due to  Numba, a dependency of OMAmer, not being yet compatible with Python 11. It should be fixed with the release of the version 0.57 of Numba. (see  https://github.com/numba/numba/issues/8304 for more details).
Unfortunately, we can't amend this requirement, but will keep this issue opened until the release of Numba 0.57, which is expected to be released soon. In the meantime, we recommend using OMArk with earlier version of Python.

**Comment by vkkodali** [comment]
Thank you @YanNevers
For now, I am able to use python 3.9.16.

**Comment by YanNevers** [comment]
Now compatible with Python 3.11.
Compatibility issue with Python 3.12 for the same reasons.

**Comment by epaule** [comment]
there is also a cgi dependency in the webapp.py that needs replacing, as cgi was removed in 3.13
