### ISSUE TITLE
Homininae prebuilt database - Problem

### ISSUE THREAD

**Issue by rlibouba** [DessimozLab/OMArk#30]
Hi, 
I'm working on the French Galaxy instance, and we want to integrate OMArk and add pre-built OMAmer databases. While testing the available databases, I encountered a problem with the Homininae.h5 database. 

Here's the error I get : 
`WARNING: The selected ancestral lineage is from the phylum rank or higher which means the target species' taxonomic division is not well sampled in our database. The results may lack accuracy.
Traceback (most recent call last):
  File "/home/rlibouba/.conda/envs/mamba/envs/omark/bin/omark", line 51, in <module>
    omark.launcher(arg)
  File "/home/rlibouba/.conda/envs/mamba/envs/omark/lib/python3.10/site-packages/omark/omark.py", line 265, in launcher
    get_omamer_qscore(omamerfile, dbpath, outdir, taxid, original_FASTA_file = original_fasta, isoform_file=isoform_file, taxonomic_rank=taxonomic_rank)
  File "/home/rlibouba/.conda/envs/mamba/envs/omark/lib/python3.10/site-packages/omark/omark.py", line 118, in get_omamer_qscore
    LOG.info('Ancestral lineage is '+closest_corr)
TypeError: can only concatenate str (not "NoneType") to str
/home/rlibouba/.conda/envs/mamba/envs/omark/lib/python3.10/site-packages/tables/file.py:113: UnclosedFileWarning: Closing remaining open file: ../db/Homininae.h5
  warnings.warn(UnclosedFileWarning(msg))`

Can you help? This error was obtained with this command line: omark -f file.omamer -d /db/Homininae.h5 -o omark_output

**Comment by YanNevers** [comment]
Dear @rlibouba,

I apologize, I missed your latest message and this issue felt through my awareness. 
If you are still needing a small test database,  I can explore the available option and try to come up with a quick solution to this issue.
