### ISSUE TITLE
Problems running omark - list index out of range

### ISSUE THREAD

**Issue by claraptzsl** [DessimozLab/OMArk#34]
Hi there,

I'm trying to run omark on a few annotations with `omark -f ${species}.omamer -d /.../LUCA-v2.0.0.h5 -o output -i ${species}.splice`. I ran omamer before with `omamer search --db /.../LUCA-v2.0.0.h5  --query ${species}.aa --out ${species}.omamer -t 12` which worked without an error message. Everytime I run omamer, i get the following error message:

`Traceback (most recent call last):
  File "/home/s-clpitz/miniforge3/envs/oma/bin/omark", line 51, in <module>
    omark.launcher(arg)
  File "/home/s-clpitz/miniforge3/envs/oma/lib/python3.11/site-packages/omark/omark.py", line 265, in launcher
    get_omamer_qscore(omamerfile, dbpath, outdir, taxid, original_FASTA_file = original_fasta, isoform_file=isoform_file, taxonomic_rank=taxonomic_rank)
  File "/home/s-clpitz/miniforge3/envs/oma/lib/python3.11/site-packages/omark/omark.py", line 85, in get_omamer_qscore
    placements = spd.get_present_lineages(full_match_data, hog_tab, tax_tab, tax_buff, sp_tab, chog_buff)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s-clpitz/miniforge3/envs/oma/lib/python3.11/site-packages/omark/species_determination.py", line 53, in get_present_lineages
    all_tax = get_close_taxa_omamer(omamdata, hog_tab, tax_tab, tax_buff, chog_buff,  allow_hog_redun =False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s-clpitz/miniforge3/envs/oma/lib/python3.11/site-packages/omark/species_determination.py", line 79, in get_close_taxa_omamer
    if 'hoglevel' not in omamerdata[0]:
                         ~~~~~~~~~~^^^
IndexError: list index out of range
/home/s-clpitz/miniforge3/envs/oma/lib/python3.11/site-packages/tables/file.py:114: UnclosedFileWarning: Closing remaining open file: /home/nas-hs/data/db/omark/LUCA-v2.0.0.h5
  warnings.warn(UnclosedFileWarning(msg))`

I ran Omark yesterday on 49 different annotations which worked completely fine. The fasta-headers in these annotations had no underlines, so I tried removing them from my fasta headers today but the same error occured. I also tried using only the first 100 proteins and also got the same problem.

Do you have any idea on how to solve this problem? 

Thank you in advance for your help!
Clara

**Comment by claraptzsl** [comment]
Hi,
sorry for the inconvenience. I found the problem: my transcript ids were inconsistent between the gtf and protein fasta file. After fixing this, it works. (Just as an information, if someone encounters the same error message.)
- Clara

**Comment by YanNevers** [comment]
Hello Clara,

Thank you for using our software and for reporting this issue.
I apologize for the late answer.
As you said, it may happen when protein identifiers in the FASTA file and ones in the splice file are not consistent. However, it should be handled in a more user friendly way, that should make it easier to spot the issue.
I am adding it to my TODO list for a future update.

Best wishes,
Yannis

**Comment by YanNevers** [comment]
I now implemented an explicit check of identifier equivalence between splice and omamer file with commit, and clean crash if they don't  (commit 5fa6f9aedde0e74671cd4d8cf213cbbb5ce393c9).
